### ISSUE TITLE
Bug on mac 

### ISSUE THREAD

**Issue by 4Blade** [matthewrdev/mfractor-installer#1]
<img width="1440" alt="screen shot 2016-10-16 at 10 06 40 pm" src="https://cloud.githubusercontent.com/assets/20342887/19423291/e44bf8a0-93ec-11e6-972e-07d7c909c0fd.png">

**Comment by matthewrdev** [comment]
@4Blade Geographically, where are you located? The server that hosts the addin is in SE Asia so that may contribute to the timeout you are seeing.

In the meantime, try downloading and installing MFractor manually:
 1. Download MFractor: http://addins.mfractor.com/releases/latest/MFractor.mpack
 2. Start Xamarin Studio
 3. Open the Addin Manager in Xamarin Studio.
 4. Select "Install from file..." from the lower left hand corner of the Addin Manager window.
 5. Browse to the location of "MFractor.mpack" and select it.
 6. This will install the addin for you.

If you'd like live support, drop into [#mfractor](https://xamarinchat.slack.com/?redir=%2Farchives%2Fmfractor) in the Xamarin Slack channel to chat.

**Comment by 4Blade** [comment]
I am so sorry about this late response.. I have been very inactive. Won't happen again.. The time out was probably due too the fact that the server is in SE Asia as you perviously said. I installed it manually and everything worked perfectly back then. Again my apologies.. Sincerely Nik Mische
